Add domain detail
twilio/twilio-python pull request #739
Opened 2023-12-08 06:34 UTC by manisha1997

# Fixes #

chore: add Twilio domain details

### Checklist
- [x] I acknowledge that all my contributions will be made under the project's license
- [ ] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [ ] I have read the [Contribution Guidelines](https://github.com/twilio/twilio-python/blob/main/CONTRIBUTING.md) and my PR follows them
- [ ] I have titled the PR appropriately
- [ ] I have updated my branch with the main branch
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation about the functionality in the appropriate .md file
- [ ] I have added inline documentation to the code I modified

If you have questions, please file a [support ticket](https://twilio.com/help/contact), or create a GitHub Issue in this repository.

2023-12-08 07:22 UTC, tiwarishubham635 requested changes
I think the preview_messaging/v1/ folder and its files can be omitted since they will be generated by OAI generator. But still, there is no loss having them beforehand.

2023-12-08 07:22 UTC, tiwarishubham635 commented on twilio/rest/__init__.py
> +        Access the Preview Twilio Domain
It should be Preview Messaging here

2023-12-08 07:22 UTC, tiwarishubham635 commented on twilio/rest/__init__.py
> +        :returns: Preview Twilio Domain
Same here, Preview Messaging Twilio Domain

2023-12-08 07:22 UTC, tiwarishubham635 commented on twilio/rest/preview_messaging/PreviewMessagingBase.py
> +        :returns: Domain for Accounts
Domain for Preview Messaging

2023-12-11 13:25 UTC, manisha1997 commented on twilio/rest/preview_messaging/PreviewMessagingBase.py
> +        :returns: Domain for Accounts
changed

2023-12-13 12:43 UTC, tiwarishubham635 approved these changes
LGTM!

2023-12-13 12:43 UTC, merged